name: Build iOS Application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2  # Adjust to your Ruby version

    - name: Install dependencies
      run: |
        sudo gem install cocoapods
        pod install
        sudo gem install fastlane

    - name: Build IPA
      run: |
        make package

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v3
      with:
        name: palera1nLoader-ipa
        path: packages/*.ipa

    - name: Clean up
      run: |
        make clean
